apiVersion: v1
kind: Namespace
metadata:
  name: lustre-build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-share-etc-pki-entitlement
  namespace: lustre-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: use-share-etc-pki-entitlement
subjects:
  - kind: ServiceAccount
    name: pipeline
  - kind: ServiceAccount
    name: builder
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: buildah-lustre-node-image
  namespace: lustre-build
spec:
  source:
    type: Git
    git:
      url: https://github.com/kincl/lustre-on-openshift.git
      revision: testing-layering
    contextDir: cluster-layering
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  paramValues:
  - name: dockerfile
    value: Containerfile
  volumes:
  - csi:
      driver: csi.sharedresource.openshift.io
      readOnly: true
      volumeAttributes:
        sharedSecret: etc-pki-entitlement
    name: etc-pki-entitlement
  output:
    image: image-registry.openshift-image-registry.svc:5000/lustre-build/lustre-node-image
