FROM image-registry.openshift-image-registry.svc:5000/openshift/driver-toolkit as build

RUN dnf --enablerepo=ubi-9-codeready-builder -y install libtool keyutils-libs-devel libmount-devel libnl3-devel libyaml-devel

RUN cd /tmp && \
    git clone git://git.whamcloud.com/fs/lustre-release.git && \
    cd lustre-release && \
    git checkout b2_15 && \
    sh autogen.sh && \
    ./configure && \
    make rpms
