kind: DaemonSet
apiVersion: apps/v1
metadata:
  generateName: mount-lustre-
  name: mount-lustre
  namespace: lustre
spec:
  selector:
    matchLabels:
      app: mount-lustre
  template:
    metadata:
      labels:
        app: mount-lustre
    spec:
      nodeSelector:
        feature.kmm.lustre: 'true'
      terminationGracePeriodSeconds: 30
      containers:
        - lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - mkdir -p /host/var/lustre && mount -t lustre -o noatime,flock fs-02ede3214f40c0f68.fsx.us-east-2.amazonaws.com@tcp:/fsx  /host/var/lustre
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - umount /host/var/lustre
          name: mount-lustre
          command:
            - sleep
            - infinity
          securityContext:
            privileged: true
          volumeMounts:
          - name: host-dev
            mountPath: /dev
          - name: host-sys
            mountPath: /sys
          - name: host
            mountPath: /host
            mountPropagation: Bidirectional
          image: image-registry.openshift-image-registry.svc:5000/lustre/lustre:4.18.0
      hostNetwork: true
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-sys
        hostPath:
          path: /sys
      - name: host
        hostPath:
          path: /
      dnsPolicy: ClusterFirst
      priorityClassName: system-node-critical
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10

